### ISSUE TITLE
iOS app not able to show the streaming from another device

### ISSUE THREAD

**Issue by shishir87** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#6]
Hi,

I am tying to develop my own iOS as per the code given in this project and I have observed the following behaviour in my app.

1. I tried running my iOS app in iPhone 6 simulator (OS version 12.1) and I could see the Live streaming successfully and able to hear the voice.

2. I tried running my iOS app in iPhone 6 physical device (OS version 12.4.6) and I could see the Live streaming successfully and able to hear the voice.

3. I am not able to see the Live streaming in iPhone11 simulator (OS version greater than 13) but I can hear the voice.

4. I am not able to see the Live streaming in iPhone 6 physical device (OS version greater than 13) but I can hear the voice.

==============   Code snippet to create Live stream video view   =============
func embedVideoView(){
        #if arch(arm64)
        // Using metal (arm64 only)
        let remoteRenderer = RTCMTLVideoView(frame: liveVideoView.frame)
        remoteRenderer.videoContentMode = .scaleAspectFill
        
        #else
        let remoteRenderer = RTCEAGLVideoView(frame: liveVideoView.frame)
        #endif
        
        self.webRTCClient.renderRemoteVideo(to: remoteRenderer)
        
       embedView(remoteRenderer, into:liveVideoView )
    }
    
    private func embedView(_ view: UIView, into containerView: UIView) {
        containerView.addSubview(view)
        view.translatesAutoresizingMaskIntoConstraints = false
        containerView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[view]|",
                                                                    options: [],
                                                                    metrics: nil,
                                                                    views: ["view": view]))
        
        containerView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[view]|",
                                                                    options: [],
                                                                    metrics: nil,
                                                                    views: ["view": view]))
        containerView.layoutIfNeeded()
    }
======================  End of Code ===================================

Please help.

**Comment by sharadrj** [comment]
hi @shishir87 ,
We investigated this issue. It seems iOS 13.1 has introduced some bugs that were fixed in subsequent versions. 

Please try with iOS 13.3. We verified that it works on our side.

**Comment by shishir87** [comment]
Thanks @sharadrj ,
I tried to run the app on simulator iPhone 8 (iOS version 13.3) but I could not see the actual video stream. Instead I could see the red colour over the view where video stream should be displayed.
But I could successfully hear the audio stream.
Please refer the attached screenshot
<img width="387" alt="Screenshot 2020-04-10 at 12 49 12 PM" src="https://user-images.githubusercontent.com/12554967/78972181-c6a89000-7b2a-11ea-9b9d-e8a5d17951ce.png">

**Comment by sharadrj** [comment]
@shishir87 , 
Can you make sure you are on 13.3.2 or greater? Or just move to 13.4 and try there.

**Comment by shishir87** [comment]
Hi @sharadrj ,

I tried on **simulator** iPhone 11 Pro max - iOS version 13.4. 
Still not able to see the video stream. But able to hear audio stream.
Check the below screenshot for reference
![Screenshot 2020-04-18 at 12 19 16 PM](https://user-images.githubusercontent.com/12554967/79630495-67243300-816f-11ea-9f07-5678d95ed1b4.png)

**Comment by shishir87** [comment]
Hi @dswamina,

I was not able to find the attribute "kCVPixelBufferIOSurfacePropertiesKey" in the project.

**Comment by hassanctech** [comment]
Closing due to inactivity.
